"""Building the committed, generated artifacts from the authored content.

Outputs are deterministic (sorted keys, fixed formatting) so `--check` can
compare them byte for byte against what is committed.
"""

import difflib
import json
import re
from dataclasses import dataclass
from pathlib import Path

from conventions_tools import vocabulary
from conventions_tools.content import Content, Convention, Requirement, requirement_sort_key
from conventions_tools.paths import (
    PRODUCT_DIR_NAME,
    REPOSITORY_URL,
    conventions_dir,
    index_file,
    vale_style_dir,
)
from conventions_tools.profiles import resolve_all

SCHEMA_VERSION = 1
NOT_WAIVABLE_FAMILIES = frozenset({"ADOPT"})
TERMINOLOGY_URL = f"{REPOSITORY_URL}/blob/main/{PRODUCT_DIR_NAME}/terminology/README.md"


@dataclass(frozen=True)
class Output:
    path: Path
    text: str


def _requirement_entry(req: Requirement) -> dict[str, object]:
    entry: dict[str, object] = {
        "aliases": list(req.aliases),
        "anchor": req.anchor,
        "convention": req.convention,
        "engine": req.engine,
        "path": req.path,
        "severity": req.severity,
        "since": req.since,
        "status": req.status,
        "title": req.title,
        "waivable": req.family not in NOT_WAIVABLE_FAMILIES,
    }
    if req.package is not None:
        entry["package"] = req.package
    if req.schema is not None:
        entry["schema"] = req.schema
    if req.replaced_by:
        entry["replaced_by"] = list(req.replaced_by)
    return entry


def _convention_entry(convention: Convention) -> dict[str, object]:
    return {
        "authority": convention.authority,
        "path": convention.path,
        "status": convention.status,
        "title": convention.title,
        "topic": convention.topic,
    }


def build_index(content: Content) -> dict[str, object]:
    resolved = resolve_all(
        content.profiles,
        content.requirements,
        {family.prefix for family in content.families},
    )
    index: dict[str, object] = {
        "schema_version": SCHEMA_VERSION,
        "repository": REPOSITORY_URL,
        "product_dir": PRODUCT_DIR_NAME,
        "conventions": {
            convention.id: _convention_entry(convention) for convention in content.conventions
        },
        "requirements": {req.id: _requirement_entry(req) for req in content.requirements},
        "profiles": {
            profile.id: {
                "display_name": profile.display_name,
                "requirements": list(profile.requirements),
                "severity": profile.severity,
            }
            for profile in resolved.values()
        },
        "vocabulary": vocabulary.project(content.terminology),
    }
    return {"conventions": {"index": index}}


def render_json(data: object) -> str:
    return json.dumps(data, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def _yaml_string(text: str) -> str:
    # A JSON string literal is a valid YAML double-quoted scalar.
    return json.dumps(text, ensure_ascii=False)


def _regex_literal(text: str) -> str:
    # Swap keys are regular expressions. The terminology schema limits alias
    # text to letters, digits, spaces, '.', '_' and '-', of which only '.' is
    # special outside a character class.
    return text.replace(".", r"\.")


def render_vale_style(swaps: list[vocabulary.ProseSwap], *, level: str, message: str) -> str:
    """A Vale substitution style mapping each alias to what to write instead."""
    lines = [
        "# Generated by `conventions generate` from terminology/global.yml. Do not edit:",
        "# change the prose-scope aliases there and regenerate.",
        "extends: substitution",
        f"message: {_yaml_string(message)}",
        f"link: {_yaml_string(TERMINOLOGY_URL)}",
        f"level: {level}",
        "ignorecase: true",
    ]
    if swaps:
        lines.append("swap:")
        lines.extend(
            f"  {_yaml_string(_regex_literal(swap.text))}: {_yaml_string(swap.suggest)}"
            for swap in swaps
        )
    else:
        lines.append("swap: {}")
    return "\n".join(lines) + "\n"


def _cell(text: str) -> str:
    return re.sub(r"([\\<>|*])", r"\\\1", text)


def _convention_link(convention: Convention, anchor: str = "") -> str:
    target = Path(convention.path).relative_to("conventions").as_posix()
    return f"{target}#{anchor}" if anchor else target


def render_readme(content: Content) -> str:
    by_id = {convention.id: convention for convention in content.conventions}
    lines = [
        "# Conventions",
        "",
        "<!-- Generated by `conventions generate` from the convention frontmatter and",
        "families.yml. Do not edit: change the frontmatter and regenerate. -->",
        "",
        "Every convention and every requirement ID, retired ones included. A requirement",
        "ID is permanent: it is never renumbered or reused.",
        "",
        "## Conventions",
        "",
        "| ID | Title | Topic | Status |",
        "| --- | --- | --- | --- |",
    ]
    lines.extend(
        f"| [{convention.id}]({_convention_link(convention)}) | {_cell(convention.title)} "
        f"| {convention.topic} | {convention.status} |"
        for convention in sorted(content.conventions, key=lambda item: item.id)
    )
    lines += [
        "",
        "## Requirements",
        "",
        "| ID | Title | Convention | Status | Severity | Engine |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for req in sorted(content.requirements, key=lambda item: requirement_sort_key(item.id)):
        link = _convention_link(by_id[req.convention], req.anchor)
        lines.append(
            f"| [{req.id}]({link}) | {_cell(req.title)} | {req.convention} "
            f"| {req.status} | {req.severity} | {req.engine} |"
        )
    lines += [
        "",
        "## Families",
        "",
        "| Prefix | Title | Topic |",
        "| --- | --- | --- |",
    ]
    lines.extend(
        f"| {family.prefix} | {_cell(family.title)} | {family.topic} |"
        for family in content.families
    )
    return "\n".join(lines) + "\n"


def build_outputs(content: Content) -> list[Output]:
    product = content.product
    styles = vale_style_dir(product)
    terms = content.terminology
    return [
        Output(index_file(product), render_json(build_index(content))),
        Output(
            styles / "Terms.yml",
            render_vale_style(
                vocabulary.prose_swaps(terms, "banned"),
                level="error",
                message="Use '%s' instead of '%s'.",
            ),
        ),
        Output(
            styles / "Discouraged.yml",
            render_vale_style(
                vocabulary.prose_swaps(terms, "discouraged"),
                level="warning",
                message="Prefer '%s' over '%s'.",
            ),
        ),
        Output(conventions_dir(product) / "README.md", render_readme(content)),
    ]


def drift(outputs: list[Output], product: Path) -> list[str]:
    """Unified diffs for every output that differs from the file on disk."""
    diffs: list[str] = []
    for output in outputs:
        current = output.path.read_text(encoding="utf-8") if output.path.exists() else ""
        if current == output.text:
            continue
        name = output.path.relative_to(product).as_posix()
        diffs.append(
            "".join(
                difflib.unified_diff(
                    current.splitlines(keepends=True),
                    output.text.splitlines(keepends=True),
                    fromfile=f"{name} (committed)",
                    tofile=f"{name} (generated)",
                )
            )
        )
    return diffs


def write(outputs: list[Output]) -> list[Path]:
    """Write every output that changed; return the paths written."""
    written: list[Path] = []
    for output in outputs:
        if output.path.exists() and output.path.read_text(encoding="utf-8") == output.text:
            continue
        output.path.parent.mkdir(parents=True, exist_ok=True)
        output.path.write_text(output.text, encoding="utf-8")
        written.append(output.path)
    return written
